# Generated by Django 5.2.6 on 2025-11-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('anio_publicacion', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizo', models.DateTimeField(auto_now=True)),
                ('editorial', models.CharField(max_length=100)),
                ('portada', models.ImageField(upload_to='portadas')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.autor')),
                ('categoria', models.ManyToManyField(to='catalogo.categoria')),
            ],
        ),
    ]
