# Generated by Django 5.2.8 on 2026-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_carrito_itemcarrito_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
