# Generated by Django 5.2.1 on 2025-11-10 17:57

import django.db.models.deletion
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.ForeignKey(default=registration.models.rol_default, on_delete=django.db.models.deletion.RESTRICT, to='registration.rol'),
        ),
    ]
